cached_tracik_kinematics:
  kinematics_solver: cached_ik_kinematics_plugin/CachedTRACKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 10
  solve_type: Speed
  # optional parameters for caching:
  max_cache_size: 10000
  min_pose_distance: 1
  min_joint_config_distance: 4