#
# Parameters for use with IK solvers which support OPW (Ortho-Parallel Wrist)
# kinematic configurations, as described in the paper "An Analytical Solution
# of the Inverse Kinematics Problem of Industrial Serial Manipulators with an
# Ortho-parallel Basis and a Spherical Wrist" by Mathias Brandstötter, Arthur
# Angerer, and Michael Hofbaur (Proceedings of the Austrian Robotics Workshop
# 2014, 22-23 May, 2014, Linz, Austria).
#
# The moveit_opw_kinematics_plugin package provides such a solver.
#
opw_kinematics_gp400:
  opw_kinematics_geometric_parameters:
    a1: 0.400
    a2: -0.250
    b: 0.0
    c1: 0.900
    c2: 0.1050
    c3: 0.1605
    c4: 0.300
  opw_kinematics_joint_offsets: [0.0, 0.0, deg(-90.0), 0.0, 0.0, 0.0]
  opw_kinematics_joint_sign_corrections: [1, 1, 1, 1, 1, 1]